### ISSUE TITLE
Invalid format '(created) (logger) (level) (message)' for '%' style

### ISSUE THREAD

**Issue by Dlayz1** [nicholaskajoh/ivy#46]
> Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\nicholaskajoh-ivy-137884b\main.py", line 21, in <module>
    init_logger()
  File "D:\nicholaskajoh-ivy-137884b\util\logger.py", line 59, in init_logger
    file_formatter = CustomJsonFormatter('(created) (logger) (level) (message)')
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pythonjsonlogger\jsonlogger.py", line 112, in __init__
    logging.Formatter.__init__(self, *args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '(created) (logger) (level) (message)' for '%' style

Does anyone faced with this issue when trying to run the program?

**Comment by Dlayz1** [comment]
python version:3.8.3

**Comment by nicholaskajoh** [comment]
Hello @Dlayz1, I suspect this error is due to pythonjsonlogger's lack of support for v3.8. Can you try Python 3.5, 3.6 or 3.7 and revert?
