### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by NaveedMaz** [nicholaskajoh/ivy#59]
Hello i am very new to this can you guide me how i can run it on simple video or webcam, yolo as detector. Thanks

**Comment by nicholaskajoh** [comment]
Hello @NaveedMaz, you can find the instructions in the [README](https://github.com/nicholaskajoh/ivy/blob/master/README.md). Is there any particular issue you're experiencing?

**Comment by harish713** [comment]
When i use python -m main command it gives this error please help
C:\Users\Dell\Desktop\Final_Year\Final_Year_Project\ivy>python -m main
Path to video file not set.
YOLO_WEIGHTS_PATH, YOLO_CONFIG_PATH, YOLO_CLASSES_PATH, YOLO_CLASSES_OF_INTEREST_PATH, and/or YOLO_CONFIDENCE_THRESHOLD not set or invalid.
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dell\Desktop\Final_Year\Final_Year_Project\ivy\main.py", line 14, in <module>
    import settings
  File "C:\Users\Dell\Desktop\Final_Year\Final_Year_Project\ivy\settings.py", line 214, in <module>
    raise Exception('One or more environment variables are either invalid or not set. ' +
Exception: One or more environment variables are either invalid or not set. Please ensure all variables are properly set.

**Comment by harish713** [comment]
https://docs.google.com/document/d/1MoDtRJxdNmXq1vJgHuBDWPuXL626i0wPJpwCbRSGtU4/edit?usp=sharing

**Comment by harish713** [comment]
And how to select the particular model in this project?

**Comment by ha-daiy** [comment]
This could help:
[https://github.com/nicholaskajoh/ivy/issues/52#issuecomment-1272508325](url)
