### ISSUE TITLE
init_logger() issue

### ISSUE THREAD

**Issue by sriks6711** [nicholaskajoh/ivy#70]
I am getting the following error when I try to run the main program -

E:\ivy>python -m main
Traceback (most recent call last):
  File "C:\Users\sriks\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sriks\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\ivy\main.py", line 21, in <module>
    init_logger()
  File "E:\ivy\util\logger.py", line 59, in init_logger
    file_formatter = CustomJsonFormatter('(created) (logger) (level) (message)')
  File "C:\Users\sriks\AppData\Local\Programs\Python\Python39\lib\site-packages\pythonjsonlogger\jsonlogger.py", line 112, in __init__
    logging.Formatter.__init__(self, *args, **kwargs)
  File "C:\Users\sriks\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 570, in __init__
    self._style.validate()
  File "C:\Users\sriks\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 423, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '(created) (logger) (level) (message)' for '%' style

**Comment by nicholaskajoh** [comment]
Can you try to run it with Python 3.5, 3.6 or 3.7?
